apiVersion: 1
datasources:
  - name: BenchResults
    uid: BenchResults
    type: postgres
    access: proxy
    url: postgres:5432
    user: bench
    database: postgres
    secureJsonData:
      password: bench
    jsonData:
      sslmode: disable
      postgresVersion: 1700
